name: webingo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core:
  cloud_firestore:
  pinput:
  form_field_validator: ^1.1.0
  lottie: ^1.3.0
  flutter_svg:
  get:
  shared_preferences:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf

    - family: AvenirBold
      fonts:
        - asset: assets/fonts/AvenirLTStd-Black.otf
